Lamazon/Lamazon.Web/Controllers/OrderController.cs
using Lamazon.Services.Implementations;
using Lamazon.Services.Interfaces;
using Lamazon.Services.ViewModels.Order;
using Lamazon.Services.ViewModels.OrderItem;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Serilog;
using Stripe.Checkout;
using System.Security.Claims;

namespace Lamazon.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        public OrderController(IOrderService orderService)
        {
            _orderService = orderService;
        }

        public IActionResult UserOrders()
        {

            // HOMEWORK
            return View();
        }

        [HttpGet]
        [Authorize]
        public IActionResult ShoppingCart()
        {
            string userIdValue = User.FindFirstValue(ClaimTypes.NameIdentifier);
            int userId = int.Parse(userIdValue);

            OrderViewModel activeOrderData = _orderService.GetActiveOrder(userId);

            return View(activeOrderData);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Summary()
        {
            string userIdValue = User.FindFirstValue(ClaimTypes.NameIdentifier);
            int userId = int.Parse(userIdValue);

            OrderViewModel activeOrderData = _orderService.GetActiveOrder(userId);

            return View(activeOrderData);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Summary([FromForm] OrderViewModel model)
        {
            try
            {
                _orderService.SubmitOrder(model);

                string userIdString = User.FindFirstValue(ClaimTypes.NameIdentifier);
                int userId = int.Parse(userIdString);

                OrderViewModel activeOrder = _orderService.GetActiveOrder(userId);

                // TODO ADD PAYMENT METHOD USING STRIPE

                // Add Stripe option
                string domain = "https://localhost:7265";

                SessionCreateOptions stripePaymentSession = new SessionCreateOptions()
                {
                    Mode = "payment",
                    LineItems = new List<SessionLineItemOptions>(),

                    SuccessUrl = $"{domain}/Order/Confirmation?orderId={model.Id}",
                    CancelUrl = $"{domain}/Order/ShoppingCart"
                };

                foreach (OrderItemViewModel orderItem in activeOrder.Items)
                {
                    long priceInCents = (long)(orderItem.Price * 100);

                    SessionLineItemOptions productItem = new SessionLineItemOptions()
                    {
                        Quantity = orderItem.Qty,
                        PriceData = new SessionLineItemPriceDataOptions()
                        {
                            UnitAmount = priceInCents,
                            Currency = "eur",
                            ProductData = new SessionLineItemPriceDataProductDataOptions()
                            {
                                Name = orderItem.Product.Name
                            }
                        }
                    };

                    stripePaymentSession.LineItems.Add(productItem);
                }

                SessionService sessionService = new SessionService();
                Session session = sessionService.Create(stripePaymentSession);

                return Redirect(session.Url);
            }
            catch (Exception ex)
            {
                Log.Error(ex, $"Internal Server Error happened for User {User.FindFirstValue(ClaimTypes.NameIdentifier)}");

                return RedirectToAction("Error", "Home");
            }
        }

        [HttpGet]
        [Authorize]
        public IActionResult Confirmation(int orderId)
        {
            OrderViewModel orderViewModel = _orderService.GetOrderById(orderId);
            _orderService.SetInactiveOrder(orderId); 

            ViewData["orderNumber"] = orderViewModel.OrderNumber;
            return View();
        }
    }
}

Lamazon/Lamazon.Web/Controllers/ProductCategoryController.cs
using Lamazon.Services.Interfaces;
using Lamazon.Services.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Lamazon.Web.Controllers;

public class ProductCategoryController : Controller
{

    private readonly IProductCategoryService _productCategoryService;
    
    public ProductCategoryController(IProductCategoryService productCategoryService)
    {
        _productCategoryService = productCategoryService;   
    }

    [HttpGet]
    public IActionResult Index()
    {
        var name = User.Claims.FirstOrDefault(x => x.ValueType == System.Security.Claims.ClaimTypes.Name);

        return View(_productCategoryService.GetAllProductCategories());
    }

    [HttpGet]
    public IActionResult Create() 
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create([FromForm] ProductCategoryViewModel category)
    {
        try
        {
            _productCategoryService.CreateProductCategory(category);
            return RedirectToAction("Index");
        }
        catch (Exception)
        {
            // TODO
            return RedirectToAction("Index");
        }
    }

    [HttpGet]
    public IActionResult Details(int id)
    {
        ProductCategoryViewModel productCategory = 
            _productCategoryService.GetProductCategoryById(id);

        return View(productCategory);
    }

    [HttpGet]
    public IActionResult Delete(int id) 
    {
        _productCategoryService.DeleteProductCategory(id);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Edit(int id) 
    {
        ProductCategoryViewModel categoryViewModel = 
            _productCategoryService.GetProductCategoryById(id);

        return View(categoryViewModel);
    }

    [HttpPost]
    public IActionResult Edit([FromForm] ProductCategoryViewModel categoryViewModel)
    {
        try
        {
            _productCategoryService.UpdateProductCategory(categoryViewModel);
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            // TODO
            return RedirectToAction("Index");
        }
    }
}

Lamazon/Lamazon.Web/Controllers/ProductController.cs
using Lamazon.Services.Interfaces;
using Lamazon.Services.ViewModels;
using Lamazon.Services.ViewModels.Product;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Lamazon.Web.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly IProductCategoryService _productCategoryService;

        public ProductController(IProductService productService, 
            IProductCategoryService productCategoryService)
        {
            _productService = productService;
            _productCategoryService = productCategoryService;
        }

        public IActionResult Index()
        {
            List<ProductViewModel> allProducts = _productService.GetAllProducts(); 
            return View(allProducts);
        }

        [HttpGet]
        [Authorize(Roles = "ADMIN")]
        public IActionResult Create() 
        { 
            CreateProductViewModel model = new CreateProductViewModel();
            List<ProductCategoryViewModel> allProductCategories =
                _productCategoryService.GetAllProductCategories();

            ViewBag.ProductCategories = new SelectList(allProductCategories, "Id", "Name");

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "ADMIN")]
        public IActionResult Create([FromForm] CreateProductViewModel model)
        {
            try
            {
                _productService.CreateProduct(model);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                // todo
                return null;
            }
        }
    }
}

Lamazon/Lamazon.Web/Controllers/UserController.cs
using Lamazon.Services.Interfaces;
using Lamazon.Services.ViewModels.User;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Lamazon.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult Register()
        {
            RegisterUserViewModel registerUserViewModel = new RegisterUserViewModel();
            return View(registerUserViewModel);
        }

        [HttpPost]
        public IActionResult Register([FromForm] RegisterUserViewModel model)
        {
            _userService.RegisterUser(model);
            return View("SuccessRegistration");
        }

        [HttpGet]
        public IActionResult Login()
        {
            LoginUserViewModel loginUserViewModel = new LoginUserViewModel();
            return View(loginUserViewModel);
        }

        [HttpPost]
        public IActionResult Login([FromForm] LoginUserViewModel model)
        {
            try
            {
                UserViewModel user = _userService.LoginUser(model);

                if (user is null)
                    return BadRequest();

                List<Claim> userClaims = new List<Claim>()
                {
                    new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                    new Claim(ClaimTypes.Email, user.Email),
                    new Claim(ClaimTypes.Name, user.FullName),
                    new Claim(ClaimTypes.Role, user.UserRoleKey)
                };

                ClaimsIdentity claimsIdentity 
                    = new ClaimsIdentity(userClaims, CookieAuthenticationDefaults.AuthenticationScheme);

                ClaimsPrincipal principal = new ClaimsPrincipal(claimsIdentity);

                HttpContext.SignInAsync(principal);

                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

Lamazon/Lamazon.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lamazon.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lamazon.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><strong>NETShop</strong></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        @if (User.IsInRole("ADMIN"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ProductCategory" asp-action="Index">Product Categories</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">All products</a>
                            </li>
                        }

                        @if (User.Identity.IsAuthenticated && User.IsInRole("CUSTOMER"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark">My orders (TODO)</a>
                            </li>
                        }

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-action="UserInfo" asp-controller="Home">My profile (TODO)</a>
                            </li>
                        }

                    </ul>

                   <ul class="navbar-nav ms-auto">

                        @if (User.Identity.IsAuthenticated == false)
                        {
                            <li class="nav-item">
                                <a class="btn btn-outline-primary" asp-area="" asp-controller="User" asp-action="Register">Register</a>
                            </li>

                            <li class="nav-item">
                                <a class="btn btn-outline-primary" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                            </li>
                        }
                        else
                        {
                            @if (User.IsInRole("CUSTOMER"))
                            {
                                <span class="label">
                                    <a asp-action="ShoppingCart" asp-controller="Order" class="nav-link text-dark">
                                        <i class="bi-basket-fill"></i>
                                    </a>
                                </span>
                            }

                            <span class="label">
                                <a class="nav-link text-dark">
                                    <strong>
                                        @User.Identity.Name
                                    </strong>
                                </a>
                            </span>

                            <li class="nav-item">
                                <a class="btn btn-outline-primary" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                            </li>
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Lamazon.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>